$f = 'd:\noida-main\src\components\NewShipments.css'
$c = Get-Content $f -Raw -Encoding UTF8

$c = $c -replace 'background-color:\s*#f5f7f9;', 'background-color: var(--bg-base);'
$c = $c -replace 'background:\s*white;', 'background: var(--bg-surface);'
$c = $c -replace 'background-color:\s*white;', 'background-color: var(--bg-surface);'
$c = $c -replace 'background:\s*#fff;', 'background: var(--bg-surface);'
$c = $c -replace 'background-color:\s*#fff;', 'background-color: var(--bg-surface);'
$c = $c -replace 'background-color:\s*#f7f9fc;', 'background-color: var(--bg-surface-2);'
$c = $c -replace 'background-color:\s*#f9fbff;', 'background-color: var(--bg-inset);'
$c = $c -replace 'background-color:\s*#f0f5ff;', 'background-color: var(--nav-active-bg);'
$c = $c -replace 'background-color:\s*#e4e9f2;', 'background-color: var(--bg-surface-2);'
$c = $c -replace 'background-color:\s*#f8f9fa;', 'background-color: var(--bg-surface-2);'
$c = $c -replace 'background:\s*#f8f9fa;', 'background: var(--bg-surface-2);'
$c = $c -replace 'background-color:\s*#f5f5f5;', 'background-color: var(--bg-surface-2);'
$c = $c -replace 'background-color:\s*#eef2ff;', 'background-color: var(--nav-active-bg);'
$c = $c -replace 'background-color:\s*#f9f9f9;', 'background-color: var(--bg-surface-2);'
$c = $c -replace 'background-color:\s*#fff3e0;', 'background-color: var(--warning-bg);'
$c = $c -replace 'background-color:\s*#ffffff;', 'background-color: var(--bg-surface);'
$c = $c -replace 'background:\s*#ffffff;', 'background: var(--bg-surface);'

$c = $c -replace 'color:\s*#2c3e50;', 'color: var(--text-primary);'
$c = $c -replace 'color:\s*#555;', 'color: var(--text-secondary);'
$c = $c -replace 'color:\s*#8f9bb3;', 'color: var(--text-muted);'
$c = $c -replace 'color:\s*#333;', 'color: var(--text-primary);'
$c = $c -replace 'color:\s*#7f8c8d;', 'color: var(--text-muted);'

$c = $c -replace 'border-bottom:\s*1px solid #eaecef;', 'border-bottom: 1px solid var(--border);'
$c = $c -replace 'border-top:\s*1px solid #eaecef;', 'border-top: 1px solid var(--border);'
$c = $c -replace 'border:\s*1px solid #e4e9f2;', 'border: 1px solid var(--border);'
$c = $c -replace 'border:\s*2px solid #e4e9f2;', 'border: 2px solid var(--border);'
$c = $c -replace 'border:\s*1px solid #ddd;', 'border: 1px solid var(--border-strong);'
$c = $c -replace 'border:\s*1px solid #e0e0e0;', 'border: 1px solid var(--border);'
$c = $c -replace 'border:\s*1px solid #ccc;', 'border: 1px solid var(--border-strong);'
$c = $c -replace 'border:\s*1px solid #eee;', 'border: 1px solid var(--border);'
$c = $c -replace 'border-bottom:\s*2px solid #eee;', 'border-bottom: 2px solid var(--border-strong);'

Set-Content $f $c -Encoding UTF8
Write-Host 'Done NewShipments.css'
